# .github/workflows/deploy-ecs.yml

name: Deploy to ECS

on:
  push:
    branches:
      - main
    paths:
      - 'hello-world/**'
      - '.github/workflows/deploy-ecs.yml'

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: hello-world-app
  ECS_CLUSTER: ecs-hello-world-cluster
  ECS_SERVICE: hello-world-service
  ECS_TASK_DEFINITION_FAMILY: hello-world-task

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}   
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication with AWS
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-ecs-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./hello-world
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 
      
  deploy-ecs-service:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-ecs-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Get ECR Repository URI
        id: get-ecr-uri
        run: | # Get ECR full URI  
          ECR_FULL_URI=$(aws ecr describe-repositories \
            --repository-names ${{ env.ECR_REPOSITORY }} \
            --query 'repositories[0].repositoryUri' \
            --output text)
          
          echo "DEBUG: ECR_FULL_URI retrieved in deploy job: $ECR_FULL_URI"
          echo "ecr_full_uri=$ECR_FULL_URI" >> $GITHUB_OUTPUT

          
      - name: Describe and Render Task Definition
        id: render-task-definition
        env:
          BUILT_IMAGE_URI: ${{ steps.get-ecr-uri.outputs.ecr_full_uri }}:${{ github.sha }}
        run: |
          echo "Built Image URI: $BUILT_IMAGE_URI"
        
          # Fetch the current active Task Definition from ECS
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION_FAMILY }} \
            --query taskDefinition --output json)
          
          # Update the image in the downloaded Task Definition JSON
          UPDATED_TASK_DEF_JSON=$(echo "$TASK_DEF_JSON" | \
            jq --arg img "$BUILT_IMAGE_URI" \
            '.containerDefinitions |= map(if .name == "hello-world-container" then .image = $img else . end)')

          # Remove unwanted fields that can cause conflicts when registering a new definition
          CLEANED_TASK_DEF_JSON=$(echo "$UPDATED_TASK_DEF_JSON" | \
            jq 'del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.compatibilities) | del(.registeredAt) | del(.registeredBy)') # Added more 'del' for robustness

          # Save the cleaned and updated JSON to a file
          echo "$CLEANED_TASK_DEF_JSON" > new-task-definition.json
          
          # Output the path to the updated task definition for the next step
          echo "task-definition-path=new-task-definition.json" >> $GITHUB_OUTPUT

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition-path }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
