name: Simple Variable Passing Workflow

on:
  push:
    branches:
      - main 

jobs:
  # Job 1: Sets a variable and outputs it
  set-my-variable-job:
    runs-on: ubuntu-latest
    outputs:
      my_variable: ${{ steps.set_output_step.outputs.my_value }}

    steps:
      - name: Set a custom variable
        id: set_output_step
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}        
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./hello-world
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # Ensure the image output is set correctly for the next step
          echo "my_value=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT # Set the output for the built image
          echo "Image set as: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"        

  # Job 2: Uses the variable from Job 1 and prints it
  use-my-variable-job:
    runs-on: ubuntu-latest
    needs: set-my-variable-job 
    steps:
      - name: Print the variable from Job 1
        run: |
          RECEIVED_VARIABLE="${{ needs.set-my-variable-job.outputs.my_variable }}"
          echo "The variable received from Job 1 is: $RECEIVED_VARIABLE"
